"""creating de_iframe_details table

Revision ID: e826f185ac59
Revises: 
Create Date: 2020-06-09 18:27:50.566995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e826f185ac59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_iframe_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iframeID', sa.Integer(), nullable=True),
    sa.Column('iframeURL', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_iframe_details')
    # ### end Alembic commands ###
